spring:
  application:
    name: club-dispatch
  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/${MONGODB_DATABASE:CLUB_DISPATCH}
      host: ${MONGODB_HOST}
      database: ${MONGODB_DATABASE:CLUB_DISPATCH}
      auto-index-creation: true
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    listener:
      simple:
        concurrency: 2
        default-requeue-rejected: false
        prefetch: 1
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          multiplier: 2
          max-interval: 5000

  feign:
    client:
      config:
        default:
          connectTimeout: 10000
          readTimeout: 25000

fidemax:
  url: ${FIDEMAX_URL:https://api.fidelimax.com.br/api}
  token: ${FIDEMAX_TOKEN:4d44f4bc-ca87-40a5-bd51-3b4f73fe1795-770}

protheus:
  loggerLevel: BASIC
  url: ${PROTHEUS_URL:http://192.168.2.54:9095}


fidemax-redemption:
  max-retires: 10
  pulse-interval: 5
  scheduler:
    cron-value: ${FIDEMAX_REDEMPTION_CRON_VALUE:0 */30 6-8 * * *}
    least-lock-time: PT30s
    most-lock-time: PT1M
    limit-rows: 200