spring:
  application:
    name: club-dispatch

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    listener:
      simple:
        concurrency: 2
        default-requeue-rejected: false
        prefetch: 1
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          multiplier: 2
          max-interval: 5000

  feign:
    client:
      config:
        default:
          connectTimeout: 10000
          readTimeout: 25000
        fidemax-client:
          AuthToken:
            - 4d44f4bc-ca87-40a5-bd51-3b4f73fe1795-770

fidemax:
  url: https://api.fidelimax.com.br/api
